//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shifter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shifter.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance of type &apos;{0}&apos; is null..
        /// </summary>
        internal static string InstanceIsNull {
            get {
                return ResourceManager.GetString("InstanceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple injection of constructors is not supported..
        /// </summary>
        internal static string MultipleConstructorInjectionIsNotSupported {
            get {
                return ResourceManager.GetString("MultipleConstructorInjectionIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type with name &apos;{0}&apos; cannot be resolved..
        /// </summary>
        internal static string NamedTypeCouldNotBeResolved {
            get {
                return ResourceManager.GetString("NamedTypeCouldNotBeResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be resolved..
        /// </summary>
        internal static string TypeCouldNotBeResolved {
            get {
                return ResourceManager.GetString("TypeCouldNotBeResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has no constructors to inject..
        /// </summary>
        internal static string TypeHasNoConstructorToInject {
            get {
                return ResourceManager.GetString("TypeHasNoConstructorToInject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an interface or an abstract class..
        /// </summary>
        internal static string TypeIsAnInterfaceOrAnAbstractClass {
            get {
                return ResourceManager.GetString("TypeIsAnInterfaceOrAnAbstractClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not inherit from {1}..
        /// </summary>
        internal static string TypeIsNotDerivedFromOtherType {
            get {
                return ResourceManager.GetString("TypeIsNotDerivedFromOtherType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type has not been registered..
        /// </summary>
        internal static string TypeNotRegistered {
            get {
                return ResourceManager.GetString("TypeNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : {1} is not assignable from {2}..
        /// </summary>
        internal static string TypesAreNotAssignableFrom {
            get {
                return ResourceManager.GetString("TypesAreNotAssignableFrom", resourceCulture);
            }
        }
    }
}
